front:
  week_reports:
    index:
      table:
        list_num: 10
  skill_profile:
    index:
      table:
        list_num: 10
back:
  controller:
    comment:
      cert_redirection:
        - 'week_reports'
        - 'skill_profiles'
  model:
    report:
      title:
        max_length: 255
    error:
      seperate: '#'
