front:
  skill_profile:
    index:
      table:
        list_num: 10
back:
  controller:
    comment:
      cert_redirection:
        - 'skill_profiles'
  model:
    article:
      title:
        max_length: 255
    error:
      seperate: '#'
    user:
      name: dummy
      email: dummy@dummy.jp
      password: password_dummy
      password_reset_token: dummy_token
