reset_passwords:
  token: dummy_token
  resend_at: <%= 2.days.ago %>
  expirenation: <%= 3 %>
  email:
    format: '[^@]+@([^@\.]+\.)+[^@\.]+'
settings:
  tab:
    group:
      - password
      - avatar

skill_profile:
  list_num: 10
article:
  title:
    max_length: 255
user:
  name: dummy
  email: dummy@example.com
  password: password_dummy
  password_reset_token: dummy_token
error:
  seperate: '#'
